# Generated by Django 4.0.3 on 2022-03-22 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_addproduct_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='product_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.DeleteModel(
            name='AllUsers',
        ),
    ]
