# Generated by Django 4.0.2 on 2022-03-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_addproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
