# Generated by Django 4.0.2 on 2022-03-24 09:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0006_category_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddProduct',
            new_name='Product',
        ),
    ]
