# Generated by Django 4.0.2 on 2022-03-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='to_delete',
            field=models.BooleanField(default=False),
        ),
    ]
